version: "3.3"
services:
  srds-cinema-1:
    hostname: srds-cinema-1
    container_name: srds-cinema-1
    image: srds-cinema:latest
    ports:
      - "8080:8080"
    environment:
      - SRDS_KEYSPACE_NAME=cinema
      - SRDS_CASSANDRA_CONTACT_POINTS=cassandra-seed
      - SRDS_CASSANDRA_PORT=9042
      - SRDS_CASSANDRA_DATACENTER=se1
