version: "3.3"
services:
  srds-stress-terser-1:
    container_name: srds-stress-terser-1
    image: srds-cinema-stress-tester:latest
    environment:
      - PYTHONUNBUFFERED=1
      - SRDS_SERVER_HOST=http://srds-cinema-1:8080
      - SRDS_MAX_SEATS_BULK=10
